### ISSUE TITLE
Display issue when comparing images with different heights

### ISSUE THREAD

**Issue by bluepeter** [junkboy0315/react-compare-image#15]
We are using your great image comparison tool in our product to compare screenshots. However, there is a display problem when we try to compare two screenshots that are the SAME widths but different heights.

For example, we try to compare:
- [long image]
- [shorter image]

You can see that these two files have the same width, but different heights.

When we compare these, the slider display is not perfect. See this screenshot:

![screenshot-localhost-3000-2019 05 22-16-00-42](https://user-images.githubusercontent.com/2158187/58214553-019f9c00-7cab-11e9-9b26-d360ddbb70a8.png)

What solution can we use to fix this?

**Comment by bluepeter** [comment]
I can "fix" the issue when I remove the `height: 100%` that is applied to the left image. But perhaps you can add some options to handle this sort of situation? I am not sure if this is a universal fix for this issue?

**Comment by bluepeter** [comment]
The problem with setting `height: auto` as a solution (as I have done), is that at the bottom of the comparison the longer image will "poke through" and show itself underneath the shorter image. See screenshot:

![screenshot-localhost-3000-2019 05 22-16-14-23](https://user-images.githubusercontent.com/2158187/58215037-eafa4480-7cac-11e9-86a7-b8f056270e4f.png)

So I think some mask `div` will need to be added? I.e., `<div style="height: 100%; background: #fff"><img src="left-image" style="height: auto; width: 100%"></div>`

**Comment by maximzah** [comment]
@bluepeter This CSS is fixing the bug:
```
<ReactCompareImage
   ...
   leftImageCss={{ height: 'auto' }}
/>
```
I think that no any universal solution the bug, because every developer has different cases and images

**Comment by junkboy0315** [comment]
@bluepeter 
Hi, if you can accept that overflowing part of the longer image is cut off, the solution would be as follows.

- Set the lower image to the right.
- Set `object-position: top` to the CSS of the left image

The overflowing part of the higher image(left image) is cut off though.

-----------------

this is because

canvas size is determined by:
- width of the parent
- right image's aspect ratio

and left image is displayed with:
- `object-fit: cover`
- `object-positoin: center`

This component currently can't handle images of different sizes very well.

**Comment by bluepeter** [comment]
Hm, thanks, but that solution isn't so great for me... it would be better if we can simply show a white area below the left image, instead of the overflowing right image.

Perhaps you can wrap each image in a `div` and allow us to pass CSS options to this wrapping `div`? I think this way we can probably use CSS to accomplish this.

I may try to fork the project to see if I can do this... I will let you know and PR if possible. But it may be easier for you to do this.

**Comment by junkboy0315** [comment]
@bluepeter 
I don't have time to spend to this project, but PR is always welcome.

**Comment by junkboy0315** [comment]
@bluepeter 
Hi, version 2 released today and it has the feature thanks to @vinyldarkscratch .
I hope this feature help you.
Demo and sample codes are in the following page.
https://react-compare-image.yuuniworks.com/?path=/story/images-with-different-aspect-ratios--same-width-comparison
