### ISSUE TITLE
Can I make this vertical and get proportion of the slider?

### ISSUE THREAD

**Issue by msaharia** [junkboy0315/react-compare-image#21]
Hi, I have 2 questions:

1. Can I make this a vertical comparison, rather than horizontal?
2. Is there a way to access what proportion of the image has been covered when a user is sliding over it? For example, I want to know if the slider is at 20% of the right image, or 50%, for example. And accept this as an input?

This will be used in a scientific application and probably a non-standard usage of `react-compare-image`. Would appreciate your inputs.

**Comment by junkboy0315** [comment]
hi @msaharia ,

about 1
Unfortunately vertical comparison is  not possible for now.

about 2
You can reference slider position via `onSliderPositionChange` callback prop.
And you can set initial slider position via `sliderPositionPercentage` prop.
But you cannot set position imperatively for now.

**Comment by msaharia** [comment]
Thank you very much. I wish vertical comparison were possible. Do you know of any alternative projects that allow it?

**Comment by junkboy0315** [comment]
I've never seen other libraries with that feature.
Not soon but I hope to have the feature.

**Comment by msaharia** [comment]
Thank you. That would be absolutely amazing!

**Comment by junkboy0315** [comment]
@msaharia 
Hi, version 2 released today and it has vertical feature thanks to @tasnimAlam .
I hope this helps you.
https://react-compare-image.yuuniworks.com/?path=/story/basic--basic-usage
