### ISSUE TITLE
Container size may not change correctly when source is changed

### ISSUE THREAD

**Issue by junkboy0315** [junkboy0315/react-compare-image#33]

**Comment by Exonalex** [comment]
have same problem. container define height in wrong way so end to cut my image. i had to edit bundle with height of container 100% but its temp fix. and i can slide under the max image size anyway. please fix

**Comment by albingroen** [comment]
I think this can also be solved by adding the image source or image id (if it's unique) as the `key` prop on the component. That way the `CompareImage` component should re-render every time the image is changed. It's not a optimal solution, but if the image sources changes often, the sizes and resolution really goes nuts.

**Comment by junkboy0315** [comment]
see https://react-compare-image.yuuniworks.com/?path=/story/images-with-different-aspect-ratios--default-behavior
or give me a reproductive sample.
