### ISSUE TITLE
Disable page 'scrolling' on mobile while comparing two images 

### ISSUE THREAD

**Issue by Greyu93** [junkboy0315/react-compare-image#55]
Hi there, is it possible to somehow stop scrolling while 'comparing' images on mobile?

**Comment by mattmagnotta** [comment]
I have been stuck for 3 days trying to find a solution. Is your prolem on iOS or Android specifically?

**Comment by junkboy0315** [comment]
Fork and replace these lines: 
https://github.com/junkboy0315/react-compare-image/blob/master/src/ReactCompareImage.tsx#L169-L171

```js
// from
if (!('touches' in e)) {
        e.preventDefault();
}

// to
e.preventDefault();
```

Be aware that the user will never be able to scroll again  if the entire screen is covered by this component.

**Comment by mattmagnotta** [comment]
`componentDidMount(){
    window.addEventListener('touchstart', this.touchStart);
    window.addEventListener('touchmove', this.preventTouch, {passive: false});
}

componentWillUnmount(){
    window.removeEventListener('touchstart', this.touchStart);
    window.removeEventListener('touchmove', this.preventTouch, {passive: false});
}

touchStart(e){
    this.firstClientX = e.touches[0].clientX;
    this.firstClientY = e.touches[0].clientY;
}

preventTouch(e){
    const minValue = 5; // threshold

    this.clientX = e.touches[0].clientX - this.firstClientX;
    this.clientY = e.touches[0].clientY - this.firstClientY;

    // Vertical scrolling does not work when you start swiping horizontally.
    if(Math.abs(this.clientX) > minValue){
        e.preventDefault();
        e.returnValue = false;
        return false;
    }
}`

This will stop the rubberband effect on mobile while still preserving scroll functionality.

**Comment by mattmagnotta** [comment]
`componentDidMount(){
    window.addEventListener('touchstart', this.touchStart);
    window.addEventListener('touchmove', this.preventTouch, {passive: false});
}

componentWillUnmount(){
    window.removeEventListener('touchstart', this.touchStart);
    window.removeEventListener('touchmove', this.preventTouch, {passive: false});
}

touchStart(e){
    this.firstClientX = e.touches[0].clientX;
    this.firstClientY = e.touches[0].clientY;
}

preventTouch(e){
    const minValue = 5; // threshold

    this.clientX = e.touches[0].clientX - this.firstClientX;
    this.clientY = e.touches[0].clientY - this.firstClientY;

    // Vertical scrolling does not work when you start swiping horizontally.
    if(Math.abs(this.clientX) > minValue){
        e.preventDefault();
        e.returnValue = false;
        return false;
    }
}`

This will remove the rubber band scrolling effect while still preserving scroll functionality.
