### ISSUE TITLE
Can't find variable: ResizeObserver

### ISSUE THREAD

**Issue by mattstuddert** [junkboy0315/react-compare-image#58]
Getting quite a few errors coming through from people using browsers that don't support ResizeObserver. Is this a known issue? [This Resize Observer](https://github.com/juggle/resize-observer) package could potentially be used to polyfill/ponyfill.

**Comment by junkboy0315** [comment]
This is intended, Could you see #51.

**Comment by mattstuddert** [comment]
Ah yes, sorry. I should have checked the closed issues first! I'll implement it myself, as there are still a reasonable amount of people experiencing that issue.
