### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by mrkenng** [junkboy0315/react-compare-image#6]
Nice script you have here! thank you! Was playing around today and all is good however can I suggest that you can add label for before and after text? Also, the ability to add for the handle, color, overlay and etc?

maybe like <ReactCompareImage leftImage="image1.jpg" rightImage="image2.jpg" leftLabel="Before" rightLabel="After" handleColor="#000000" lineColor="#000000" overlayHover />;

**Comment by OscarCR88** [comment]
I think that's a quite open feature request, because the position, and stiliyng of the label. It'd be interesting to see how you guys solve that.

**Comment by junkboy0315** [comment]
@mrkenng 
Today, I released beta version of this library including label functions.
As this beta version uses `Hooks`, it works only with `react` & `react-dom` > v16.8 though.

`yarn add react-compare-image@beta`

sample(in the middle of the page):
https://v1--hungry-wiles-4117ce.netlify.com/
