### ISSUE TITLE
Skeleton is only half shown on mobile

### ISSUE THREAD

**Issue by OscarCR88** [junkboy0315/react-compare-image#7]
Hi there...
 I don't know if it's a local issue with my css, but on mobile landscape, the skeleton is only half shown because you're setting `overflow:hidden` to the skeleton container's style, which happens to be the same container's style as data-enzyme. Perhaps creating an own style, for the skeleton container, withohut having `overflow: hidden`, solves the issue. Can you comment on this subject?

Thank you

**Comment by OscarCR88** [comment]
As a matter of fact, I can confirm that creating a separate style for the skeleton's container, and removing `overflow: hidden` from it, solves the problem

**Comment by junkboy0315** [comment]
I am glad to hear that you solved the problem!

**Comment by OscarCR88** [comment]
Yeah, I solved locally, but, would you accept a PR with theese fixes

**Comment by junkboy0315** [comment]
Oh, I may have been misunderstood. I'm not good at English.

PR is welcome!
