### ISSUE TITLE
Animate Slider handles

### ISSUE THREAD

**Issue by jhig85** [junkboy0315/react-compare-image#8]
Just wondering if anybody knew of a way to animate the slider handles when scrolled into view of the slider. Basically once you scroll into view the slider would slide to the left, then to the right and then finally go to the default sliderPositionPercentage that you set. Thanks!

**Comment by junkboy0315** [comment]
@jhig85 
Hi, thank you for using my component.
Unfortunately it's not possible to animate the slider position by now.
You can only set the default position of the slider.

**Comment by jhig85** [comment]
Thanks for responding! I thought that would be the answer but wanted to check first. Really like the the component by the way. Super easy to use.
